// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: municion.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MunicionServiceClient is the client API for MunicionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MunicionServiceClient interface {
	// Método para solicitar munición
	RequestMunicion(ctx context.Context, in *MunicionRequest, opts ...grpc.CallOption) (*MunicionResponse, error)
}

type municionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMunicionServiceClient(cc grpc.ClientConnInterface) MunicionServiceClient {
	return &municionServiceClient{cc}
}

func (c *municionServiceClient) RequestMunicion(ctx context.Context, in *MunicionRequest, opts ...grpc.CallOption) (*MunicionResponse, error) {
	out := new(MunicionResponse)
	err := c.cc.Invoke(ctx, "/municion.MunicionService/RequestMunicion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MunicionServiceServer is the server API for MunicionService service.
// All implementations must embed UnimplementedMunicionServiceServer
// for forward compatibility
type MunicionServiceServer interface {
	// Método para solicitar munición
	RequestMunicion(context.Context, *MunicionRequest) (*MunicionResponse, error)
	mustEmbedUnimplementedMunicionServiceServer()
}

// UnimplementedMunicionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMunicionServiceServer struct {
}

func (UnimplementedMunicionServiceServer) RequestMunicion(context.Context, *MunicionRequest) (*MunicionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestMunicion not implemented")
}
func (UnimplementedMunicionServiceServer) mustEmbedUnimplementedMunicionServiceServer() {}

// UnsafeMunicionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MunicionServiceServer will
// result in compilation errors.
type UnsafeMunicionServiceServer interface {
	mustEmbedUnimplementedMunicionServiceServer()
}

func RegisterMunicionServiceServer(s grpc.ServiceRegistrar, srv MunicionServiceServer) {
	s.RegisterService(&MunicionService_ServiceDesc, srv)
}

func _MunicionService_RequestMunicion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MunicionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MunicionServiceServer).RequestMunicion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/municion.MunicionService/RequestMunicion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MunicionServiceServer).RequestMunicion(ctx, req.(*MunicionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MunicionService_ServiceDesc is the grpc.ServiceDesc for MunicionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MunicionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "municion.MunicionService",
	HandlerType: (*MunicionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestMunicion",
			Handler:    _MunicionService_RequestMunicion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "municion.proto",
}
