// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: municion.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definición del mensaje para la solicitud de munición
type MunicionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamId  int32 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	AtCount int32 `protobuf:"varint,2,opt,name=at_count,json=atCount,proto3" json:"at_count,omitempty"`
	MpCount int32 `protobuf:"varint,3,opt,name=mp_count,json=mpCount,proto3" json:"mp_count,omitempty"`
}

func (x *MunicionRequest) Reset() {
	*x = MunicionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_municion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MunicionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MunicionRequest) ProtoMessage() {}

func (x *MunicionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_municion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MunicionRequest.ProtoReflect.Descriptor instead.
func (*MunicionRequest) Descriptor() ([]byte, []int) {
	return file_municion_proto_rawDescGZIP(), []int{0}
}

func (x *MunicionRequest) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *MunicionRequest) GetAtCount() int32 {
	if x != nil {
		return x.AtCount
	}
	return 0
}

func (x *MunicionRequest) GetMpCount() int32 {
	if x != nil {
		return x.MpCount
	}
	return 0
}

// Definición del mensaje para la respuesta de la solicitud de munición
type MunicionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Approved    bool  `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	AvailableAt int32 `protobuf:"varint,2,opt,name=available_at,json=availableAt,proto3" json:"available_at,omitempty"`
	AvailableMp int32 `protobuf:"varint,3,opt,name=available_mp,json=availableMp,proto3" json:"available_mp,omitempty"`
}

func (x *MunicionResponse) Reset() {
	*x = MunicionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_municion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MunicionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MunicionResponse) ProtoMessage() {}

func (x *MunicionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_municion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MunicionResponse.ProtoReflect.Descriptor instead.
func (*MunicionResponse) Descriptor() ([]byte, []int) {
	return file_municion_proto_rawDescGZIP(), []int{1}
}

func (x *MunicionResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *MunicionResponse) GetAvailableAt() int32 {
	if x != nil {
		return x.AvailableAt
	}
	return 0
}

func (x *MunicionResponse) GetAvailableMp() int32 {
	if x != nil {
		return x.AvailableMp
	}
	return 0
}

var File_municion_proto protoreflect.FileDescriptor

var file_municion_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x22, 0x60, 0x0a, 0x0f, 0x4d, 0x75,
	0x6e, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x74, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x74, 0x0a, 0x10,
	0x4d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x4d, 0x70, 0x32, 0x5b, 0x0a, 0x0f, 0x4d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x4d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x63,
	0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x2e, 0x4d,
	0x75, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_municion_proto_rawDescOnce sync.Once
	file_municion_proto_rawDescData = file_municion_proto_rawDesc
)

func file_municion_proto_rawDescGZIP() []byte {
	file_municion_proto_rawDescOnce.Do(func() {
		file_municion_proto_rawDescData = protoimpl.X.CompressGZIP(file_municion_proto_rawDescData)
	})
	return file_municion_proto_rawDescData
}

var file_municion_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_municion_proto_goTypes = []interface{}{
	(*MunicionRequest)(nil),  // 0: municion.MunicionRequest
	(*MunicionResponse)(nil), // 1: municion.MunicionResponse
}
var file_municion_proto_depIdxs = []int32{
	0, // 0: municion.MunicionService.RequestMunicion:input_type -> municion.MunicionRequest
	1, // 1: municion.MunicionService.RequestMunicion:output_type -> municion.MunicionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_municion_proto_init() }
func file_municion_proto_init() {
	if File_municion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_municion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MunicionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_municion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MunicionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_municion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_municion_proto_goTypes,
		DependencyIndexes: file_municion_proto_depIdxs,
		MessageInfos:      file_municion_proto_msgTypes,
	}.Build()
	File_municion_proto = out.File
	file_municion_proto_rawDesc = nil
	file_municion_proto_goTypes = nil
	file_municion_proto_depIdxs = nil
}
